-- UDE Governance sample data setup (fast-load synthetic data)

-- Create schema for governance entities
CREATE SCHEMA IF NOT EXISTS UNIVERSAL_DATA_PLATFORM.GOVERNANCE;

-- Assets
CREATE OR REPLACE TABLE UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_ASSETS (
  ASSET_ID STRING,
  ASSET_NAME STRING,
  ASSET_TYPE STRING,
  DATABASE_NAME STRING,
  SCHEMA_NAME STRING,
  DOMAIN STRING,
  SUBJECT_TYPE STRING,
  SENSITIVITY_TIER INTEGER,
  OWNER STRING,
  IS_ACTIVE BOOLEAN,
  CREATED_AT TIMESTAMP_NTZ,
  UPDATED_AT TIMESTAMP_NTZ
);

-- Scan runs
CREATE OR REPLACE TABLE UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_SCAN_RUNS (
  RUN_ID STRING,
  STARTED_AT TIMESTAMP_NTZ,
  FINISHED_AT TIMESTAMP_NTZ,
  SCANNER_VERSION STRING,
  SOURCE STRING,
  STATUS STRING,
  ASSETS_SCANNED NUMBER,
  ROWS_SCANNED NUMBER,
  TOKENS_USED NUMBER,
  RUN_COST_USD NUMBER
);

-- Findings
CREATE OR REPLACE TABLE UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_FINDINGS (
  FINDING_ID STRING,
  ASSET_ID STRING,
  COLUMN_NAME STRING,
  DETECTED_TYPE STRING,
  CONFIDENCE_SCORE NUMBER,
  MODEL_VERSION STRING,
  RUN_ID STRING,
  DOMAIN STRING,
  SUBJECT_TYPE STRING,
  RATIONALE STRING,
  CREATED_AT TIMESTAMP_NTZ
);

-- Decisions
CREATE OR REPLACE TABLE UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_DECISIONS (
  DECISION_ID STRING,
  FINDING_ID STRING,
  DECISION STRING,
  CORRECTED_TAG STRING,
  REVIEWER STRING,
  REASON STRING,
  DECIDED_AT TIMESTAMP_NTZ,
  APPLIED_AT TIMESTAMP_NTZ,
  APPLIED_BY STRING,
  REVERTED_FLAG BOOLEAN
);

-- Policies
CREATE OR REPLACE TABLE UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_POLICIES (
  POLICY_ID STRING,
  POLICY_NAME STRING,
  POLICY_TYPE STRING,
  POLICY_SQL STRING,
  VERSION STRING,
  CREATED_AT TIMESTAMP_NTZ
);

-- Policy bindings
CREATE OR REPLACE TABLE UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_POLICY_BINDINGS (
  BINDING_ID STRING,
  ASSET_ID STRING,
  COLUMN_NAME STRING,
  POLICY_ID STRING,
  STATUS STRING,
  BOUND_AT TIMESTAMP_NTZ
);

-- Subjects
CREATE OR REPLACE TABLE UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_SUBJECTS (
  SUBJECT_ID STRING,
  SUBJECT_TYPE STRING,
  EMAIL STRING,
  SSO STRING,
  FULL_NAME STRING,
  CREATED_AT TIMESTAMP_NTZ
);

-- Privacy requests
CREATE OR REPLACE TABLE UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_PRIVACY_REQUESTS (
  REQUEST_ID STRING,
  SUBJECT_ID STRING,
  REQUEST_TYPE STRING,
  STATUS STRING,
  SCOPE STRING,
  NOTES STRING,
  SUBMITTED_AT TIMESTAMP_NTZ,
  COMPLETED_AT TIMESTAMP_NTZ
);

-- Usage metrics
CREATE OR REPLACE TABLE UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_USAGE_METRICS (
  EVENT_ID STRING,
  EVENT_TIME TIMESTAMP_NTZ,
  USER_NAME STRING,
  FUNCTION_NAME STRING,
  TOKENS NUMBER,
  COST_USD NUMBER,
  CONTEXT STRING,
  RUN_ID STRING
);

-- Seed assets aligned to UDE domains
INSERT INTO UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_ASSETS
(ASSET_ID, ASSET_NAME, ASSET_TYPE, DATABASE_NAME, SCHEMA_NAME, DOMAIN, SUBJECT_TYPE, SENSITIVITY_TIER, OWNER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES
  ('A1','UNIVERSAL_DATA_PLATFORM.GUEST_ANALYTICS.GUEST_PROFILES','TABLE','UNIVERSAL_DATA_PLATFORM','GUEST_ANALYTICS','Guest Analytics','consumer',3,'guest_analytics_team',TRUE, DATEADD('day',-30,CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP()),
  ('A2','UNIVERSAL_DATA_PLATFORM.REVENUE_ANALYTICS.TICKET_SALES','TABLE','UNIVERSAL_DATA_PLATFORM','REVENUE_ANALYTICS','Revenue','consumer',2,'revenue_team',TRUE, DATEADD('day',-60,CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP()),
  ('A3','UNIVERSAL_DATA_PLATFORM.STAFF_MANAGEMENT.EMPLOYEE_PROFILES','TABLE','UNIVERSAL_DATA_PLATFORM','STAFF_MANAGEMENT','HR','team_member',4,'hr_team',TRUE, DATEADD('day',-200,CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP());

-- Seed scan runs
INSERT INTO UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_SCAN_RUNS
(RUN_ID, STARTED_AT, FINISHED_AT, SCANNER_VERSION, SOURCE, STATUS, ASSETS_SCANNED, ROWS_SCANNED, TOKENS_USED, RUN_COST_USD)
VALUES
  ('R1', DATEADD('day',-1,CURRENT_TIMESTAMP()), DATEADD('day',-1,DATEADD('minute',10,CURRENT_TIMESTAMP())), 'v1.2.0', 'scheduled', 'completed', 3, 500000, 120000, 6.00),
  ('R2', DATEADD('hour',-3,CURRENT_TIMESTAMP()), DATEADD('hour',-3,DATEADD('minute',8,CURRENT_TIMESTAMP())), 'v1.2.0', 'manual', 'completed', 2, 250000, 70000, 3.50);

-- Seed findings mapped to actual UDE columns
INSERT INTO UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_FINDINGS
(FINDING_ID, ASSET_ID, COLUMN_NAME, DETECTED_TYPE, CONFIDENCE_SCORE, MODEL_VERSION, RUN_ID, DOMAIN, SUBJECT_TYPE, RATIONALE, CREATED_AT)
VALUES
  ('F1','A1','EMAIL_ADDRESS','EMAIL',99,'mv_2024_08','R1','Guest Analytics','consumer','Matches email pattern and examples', DATEADD('day',-1,CURRENT_TIMESTAMP())),
  ('F2','A1','PHONE_NUMBER','PHONE',96,'mv_2024_08','R1','Guest Analytics','consumer','Consistent with E.164 formats', DATEADD('day',-1,CURRENT_TIMESTAMP())),
  ('F3','A3','EMPLOYEE_EMAIL','EMAIL',100,'mv_2024_08','R1','HR','team_member','Corporate email domain patterns', DATEADD('day',-1,CURRENT_TIMESTAMP())),
  ('F4','A3','FIRST_NAME','NAME',85,'mv_2024_08','R2','HR','team_member','Name-like tokens with high support', DATEADD('hour',-3,CURRENT_TIMESTAMP()));

-- Seed decisions
INSERT INTO UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_DECISIONS
(DECISION_ID, FINDING_ID, DECISION, CORRECTED_TAG, REVIEWER, REASON, DECIDED_AT, APPLIED_AT, APPLIED_BY, REVERTED_FLAG)
VALUES
  ('D1','F1','accept',NULL,'alice','Email for consumers should be masked', DATEADD('hour',-22,CURRENT_TIMESTAMP()), DATEADD('hour',-21,CURRENT_TIMESTAMP()), 'system', FALSE),
  ('D2','F2','reject',NULL,'bob','Column is hashed; not direct phone', DATEADD('hour',-21,CURRENT_TIMESTAMP()), NULL, NULL, FALSE),
  ('D3','F3','accept',NULL,'carol','Team member email is Tier 4 protected', DATEADD('hour',-20,CURRENT_TIMESTAMP()), DATEADD('hour',-19,CURRENT_TIMESTAMP()), 'system', FALSE),
  ('D4','F4','correct','PERSON_NAME','dave','Use PERSON_NAME to distinguish from legal entity', DATEADD('hour',-2,CURRENT_TIMESTAMP()), DATEADD('hour',-1,CURRENT_TIMESTAMP()), 'dave', FALSE);

-- Seed policies
INSERT INTO UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_POLICIES
(POLICY_ID, POLICY_NAME, POLICY_TYPE, POLICY_SQL, VERSION, CREATED_AT)
VALUES
  ('P1','MASK_EMAIL_CONSUMER','MASKING','CREATE OR REPLACE MASKING POLICY ...', '1.0', DATEADD('day',-7,CURRENT_TIMESTAMP())),
  ('P2','MASK_PII_GENERIC','MASKING','CREATE OR REPLACE MASKING POLICY ...', '1.0', DATEADD('day',-7,CURRENT_TIMESTAMP())),
  ('P3','ROW_ACCESS_HR_TIER4','ROW_ACCESS','CREATE OR REPLACE ROW ACCESS POLICY ...', '1.1', DATEADD('day',-2,CURRENT_TIMESTAMP()));

-- Seed policy bindings
INSERT INTO UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_POLICY_BINDINGS
(BINDING_ID, ASSET_ID, COLUMN_NAME, POLICY_ID, STATUS, BOUND_AT)
VALUES
  ('B1','A1','EMAIL_ADDRESS','P1','applied', DATEADD('hour',-21,CURRENT_TIMESTAMP())),
  ('B2','A3',NULL,'P3','applied', DATEADD('hour',-19,CURRENT_TIMESTAMP()));

-- Seed subjects
INSERT INTO UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_SUBJECTS
(SUBJECT_ID, SUBJECT_TYPE, EMAIL, SSO, FULL_NAME, CREATED_AT)
VALUES
  ('S1','consumer','guest1@example.com',NULL,'Alex Guest', DATEADD('day',-90,CURRENT_TIMESTAMP())),
  ('S2','team_member','employee1@universalparks.com','U123456','Jordan Team', DATEADD('day',-400,CURRENT_TIMESTAMP()));

-- Seed privacy requests
INSERT INTO UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_PRIVACY_REQUESTS
(REQUEST_ID, SUBJECT_ID, REQUEST_TYPE, STATUS, SCOPE, NOTES, SUBMITTED_AT, COMPLETED_AT)
VALUES
  ('PR1','S1','delete','completed','consumer','CCPA delete for guest', DATEADD('day',-10,CURRENT_TIMESTAMP()), DATEADD('day',-7,CURRENT_TIMESTAMP())),
  ('PR2','S2','access','completed','team_member','HR data export; do not modify records', DATEADD('day',-5,CURRENT_TIMESTAMP()), DATEADD('day',-4,CURRENT_TIMESTAMP())),
  ('PR3','S1','opt_out','in_progress','consumer','Marketing opt-out', DATEADD('day',-2,CURRENT_TIMESTAMP()), NULL);

-- Seed usage metrics
INSERT INTO UNIVERSAL_DATA_PLATFORM.GOVERNANCE.DG_USAGE_METRICS
(EVENT_ID, EVENT_TIME, USER_NAME, FUNCTION_NAME, TOKENS, COST_USD, CONTEXT, RUN_ID)
VALUES
  ('U1', DATEADD('day',-1,CURRENT_TIMESTAMP()), 'svc_scanner', 'CLASSIFY', 60000, 3.00, 'scan run R1', 'R1'),
  ('U2', DATEADD('hour',-3,CURRENT_TIMESTAMP()), 'svc_scanner', 'CLASSIFY', 35000, 1.75, 'scan run R2', 'R2'),
  ('U3', DATEADD('hour',-1,CURRENT_TIMESTAMP()), 'alice', 'COMPLETE', 5000, 0.25, 'generate masking SQL', NULL);


