-- Comcast Cybersecurity Demo - Full setup script
-- Run as SYSADMIN in DHALL_AWS1 account
-- Total runtime: ~5 minutes (50M data generation dominates)

-- 0. Database, schema, warehouse
CREATE DATABASE IF NOT EXISTS COMCAST_CYBER_DEMO;
CREATE SCHEMA IF NOT EXISTS COMCAST_CYBER_DEMO.CERT_SECURITY;
CREATE WAREHOUSE IF NOT EXISTS COMCAST_DEMO_WH WITH WAREHOUSE_SIZE='LARGE' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
USE DATABASE COMCAST_CYBER_DEMO;
USE SCHEMA CERT_SECURITY;
USE WAREHOUSE COMCAST_DEMO_WH;

-- 1. Reference dimensions
-- See README for full DDL of PARTNERS, COMPLIANCE_RULES, COMPLIANCE_DOCUMENTS

-- 2. CERTIFICATES fact table (50M rows)
-- See README for full DDL

-- 3. Streaming landing + simulator (Snowpipe Streaming-equivalent for demo)
-- RAW_CERTIFICATE_EVENTS, SIMULATE_STREAMING_BATCH proc, STREAMING_SIMULATOR_TASK

-- 4. Dynamic Table pipeline
-- DT_CERTS_CLEANED, DT_CERTS_ENRICHED, DT_COMPLIANCE_DASHBOARD

-- 5. Time-aware views
-- V_CERTIFICATES_FULL (over 50M base), V_CERTIFICATES_LIVE (over enriched DT)

-- 6. Cortex Analyst semantic view
-- CERT_COMPLIANCE_SV with 14 dimensions and 8 metrics

-- 7. Cortex Search service
-- CERT_COMPLIANCE_SEARCH with snowflake-arctic-embed-l-v2.0

-- 8. Cortex Agent
-- CERT_COMPLIANCE_AGENT combining the semantic view and search service

-- 9. SPCS infrastructure
-- APP_REPO image repository, COMCAST_CERT_APP_POOL compute pool

-- 10. Snowflake Postgres for OLTP coexistence
-- CERT_OLTP_DB STANDARD_M instance

-- DEMO START COMMANDS (run live during meeting):
-- ALTER TASK COMCAST_CYBER_DEMO.CERT_SECURITY.STREAMING_SIMULATOR_TASK RESUME;
-- SELECT * FROM COMCAST_CYBER_DEMO.CERT_SECURITY.RAW_CERTIFICATE_EVENTS ORDER BY event_timestamp DESC LIMIT 5;
-- SHOW DYNAMIC TABLES IN SCHEMA COMCAST_CYBER_DEMO.CERT_SECURITY;
-- SHOW ENDPOINTS IN SERVICE COMCAST_CYBER_DEMO.CERT_SECURITY.CERT_CHAT_SERVICE;

-- DEMO STOP COMMANDS (after meeting):
-- ALTER TASK COMCAST_CYBER_DEMO.CERT_SECURITY.STREAMING_SIMULATOR_TASK SUSPEND;
-- ALTER COMPUTE POOL COMCAST_CERT_APP_POOL SUSPEND;
-- ALTER POSTGRES INSTANCE CERT_OLTP_DB SUSPEND;
-- ALTER WAREHOUSE COMCAST_DEMO_WH SUSPEND;
