-- Comcast Business Polus Platform Streamlit App Setup
-- Run this script to set up the Streamlit app in Snowflake

-- Step 1: Create a stage for Streamlit files
CREATE OR REPLACE STAGE POLUS_STREAMLIT_STAGE
DIRECTORY = (ENABLE = TRUE);

-- Step 2: Create the Streamlit app
CREATE OR REPLACE STREAMLIT COMCAST_BUSINESS_POLUS_APP
ROOT_LOCATION = '@POLUS_STREAMLIT_STAGE'
MAIN_FILE = '/streamlit_app.py'
QUERY_WAREHOUSE = 'COMPUTE_WH'
COMMENT = 'Comcast Business Polus Platform Analytics Dashboard';

-- Step 3: Grant necessary database and schema permissions
GRANT USAGE ON DATABASE POLUS_PLATFORM TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT USAGE ON SCHEMA POLUS_PLATFORM.ATLAS_INTERNAL TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT USAGE ON SCHEMA POLUS_PLATFORM.NEXUS_CUSTOMER TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT USAGE ON SCHEMA POLUS_PLATFORM.THREAT_INTEL TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT USAGE ON SCHEMA POLUS_PLATFORM.COMPLIANCE TO APPLICATION COMCAST_BUSINESS_POLUS_APP;

-- Step 4: Grant SELECT permissions on all required tables and views
-- Atlas Internal permissions
GRANT SELECT ON TABLE POLUS_PLATFORM.ATLAS_INTERNAL.CUSTOMER_INSIGHTS TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT SELECT ON VIEW POLUS_PLATFORM.ATLAS_INTERNAL.COST_ANALYSIS TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT SELECT ON VIEW POLUS_PLATFORM.ATLAS_INTERNAL.TOKEN_CONSUMPTION_ESTIMATE TO APPLICATION COMCAST_BUSINESS_POLUS_APP;

-- Nexus Customer permissions  
GRANT SELECT ON TABLE POLUS_PLATFORM.NEXUS_CUSTOMER.CUSTOMER_ANALYTICS TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT SELECT ON VIEW POLUS_PLATFORM.NEXUS_CUSTOMER.CB_SERVICE_DASHBOARD TO APPLICATION COMCAST_BUSINESS_POLUS_APP;

-- Threat Intelligence permissions
GRANT SELECT ON TABLE POLUS_PLATFORM.THREAT_INTEL.SECURITY_EDGE_EVENTS TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT SELECT ON TABLE POLUS_PLATFORM.THREAT_INTEL.SECURITY_EDGE_PATTERNS TO APPLICATION COMCAST_BUSINESS_POLUS_APP;

-- Compliance permissions
GRANT SELECT ON TABLE POLUS_PLATFORM.COMPLIANCE.PCI_COMPLIANCE_TRACKING TO APPLICATION COMCAST_BUSINESS_POLUS_APP;

-- Step 5: Grant function execution permissions
GRANT USAGE ON FUNCTION POLUS_PLATFORM.COMPLIANCE.GENERATE_PCI_REPORT(STRING) TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT USAGE ON FUNCTION POLUS_PLATFORM.ATLAS_INTERNAL.NATURAL_LANGUAGE_QUERY(STRING) TO APPLICATION COMCAST_BUSINESS_POLUS_APP;
GRANT USAGE ON FUNCTION POLUS_PLATFORM.THREAT_INTEL.CHECK_SECURITY_EDGE_PATTERN(STRING, STRING) TO APPLICATION COMCAST_BUSINESS_POLUS_APP;

-- Step 6: Create a role for Streamlit app users (optional)
CREATE OR REPLACE ROLE POLUS_STREAMLIT_USER;

-- Grant the role access to the Streamlit app
GRANT USAGE ON STREAMLIT COMCAST_BUSINESS_POLUS_APP TO ROLE POLUS_STREAMLIT_USER;

-- Grant basic warehouse access
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE POLUS_STREAMLIT_USER;

-- Step 7: Display app information
SHOW STREAMLITS LIKE 'COMCAST_BUSINESS_POLUS_APP';

-- Step 8: Instructions for file upload
/*
To complete the setup:

1. Upload the streamlit_app.py file to the stage:
   PUT file:///path/to/streamlit_app.py @POLUS_STREAMLIT_STAGE overwrite=true;

2. Upload any additional files if needed:
   PUT file:///path/to/requirements.txt @POLUS_STREAMLIT_STAGE overwrite=true;

3. Verify the files are uploaded:
   LIST @POLUS_STREAMLIT_STAGE;

4. Start the Streamlit app:
   ALTER STREAMLIT COMCAST_BUSINESS_POLUS_APP SET QUERY_WAREHOUSE = 'COMPUTE_WH';

5. Get the app URL:
   SHOW STREAMLITS LIKE 'COMCAST_BUSINESS_POLUS_APP';
   
6. Access the app using the URL from the previous command
*/

-- Optional: Create sample data refresh task
CREATE OR REPLACE TASK POLUS_PLATFORM.ATLAS_INTERNAL.REFRESH_CUSTOMER_METRICS
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = 'USING CRON 0 */6 * * * America/New_York'  -- Every 6 hours
AS
  -- Update customer risk scores and metrics
  UPDATE POLUS_PLATFORM.ATLAS_INTERNAL.CUSTOMER_INSIGHTS 
  SET risk_score = risk_score + (RANDOM() - 0.5) * 0.5
  WHERE ABS(risk_score + (RANDOM() - 0.5) * 0.5) <= 10;

-- Enable the task (optional)
-- ALTER TASK POLUS_PLATFORM.ATLAS_INTERNAL.REFRESH_CUSTOMER_METRICS RESUME;