-- Grants required for the CRM Customer 360 application service to invoke its tools.
--
-- In App Runtime owner's-rights mode, queries execute as the role that OWNS the
-- application service. All objects below and the CRM_DASHBOARD application
-- service are owned by SYSADMIN, so these grants are already satisfied.
--
-- If you run the app under a different role (APP_ROLE), apply these grants:

-- Structured analytics (Cortex Analyst over the semantic view + Gold tables)
GRANT SELECT ON SEMANTIC VIEW FIVETRAN_CRM_CUSTOMER360.ANALYTICS.CUSTOMER_360_ANALYTICS TO ROLE APP_ROLE;
GRANT USAGE ON DATABASE FIVETRAN_CRM_CUSTOMER360 TO ROLE APP_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_CRM_CUSTOMER360.GOLD TO ROLE APP_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FIVETRAN_CRM_CUSTOMER360.GOLD TO ROLE APP_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_CRM_CUSTOMER360.ANALYTICS TO ROLE APP_ROLE;

-- Unstructured search
GRANT USAGE ON CORTEX SEARCH SERVICE FIVETRAN_CRM_CUSTOMER360.ANALYTICS.ADVISOR_NOTES_SEARCH TO ROLE APP_ROLE;

-- Cortex Agent (REST :run)
GRANT USAGE ON AGENT FIVETRAN_CRM_CUSTOMER360.ANALYTICS.CUSTOMER360_AGENT TO ROLE APP_ROLE;

-- Fivetran simulator UDFs
GRANT USAGE ON FUNCTION FIVETRAN_CRM_CUSTOMER360.ANALYTICS.GET_FIVETRAN_CONNECTOR_STATUS(VARCHAR) TO ROLE APP_ROLE;
GRANT USAGE ON FUNCTION FIVETRAN_CRM_CUSTOMER360.ANALYTICS.GET_FIVETRAN_SYNC_HISTORY(VARCHAR) TO ROLE APP_ROLE;
GRANT USAGE ON FUNCTION FIVETRAN_CRM_CUSTOMER360.ANALYTICS.TRIGGER_FIVETRAN_SYNC(VARCHAR) TO ROLE APP_ROLE;

-- Managed MCP server (for external MCP clients)
GRANT USAGE ON MCP SERVER FIVETRAN_CRM_CUSTOMER360.ANALYTICS.CUSTOMER360_MCP_SERVER TO ROLE APP_ROLE;
