-- Grants required for the Retail Dashboard application service to invoke its tools.
--
-- In App Runtime owner's-rights mode, queries execute as the role that OWNS the
-- application service. All objects below and the RETAIL_DASHBOARD application
-- service are owned by SYSADMIN, so these grants are already satisfied.
--
-- If you run the app under a different role (APP_ROLE), apply these grants:

-- SET app_role = 'APP_ROLE';

-- Structured analytics (Cortex Analyst over the semantic view + Gold tables)
GRANT SELECT ON SEMANTIC VIEW FIVETRAN_RETAIL_DEMO.ANALYTICS.RETAIL_ANALYTICS TO ROLE APP_ROLE;
GRANT USAGE ON DATABASE FIVETRAN_RETAIL_DEMO TO ROLE APP_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_RETAIL_DEMO.GOLD TO ROLE APP_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA FIVETRAN_RETAIL_DEMO.GOLD TO ROLE APP_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_RETAIL_DEMO.ANALYTICS TO ROLE APP_ROLE;

-- Unstructured search
GRANT USAGE ON CORTEX SEARCH SERVICE FIVETRAN_RETAIL_DEMO.ANALYTICS.PRODUCT_REVIEW_SEARCH TO ROLE APP_ROLE;

-- Cortex Agent (REST :run)
GRANT USAGE ON AGENT FIVETRAN_RETAIL_DEMO.ANALYTICS.RETAIL_AGENT TO ROLE APP_ROLE;

-- Fivetran simulator UDFs
GRANT USAGE ON FUNCTION FIVETRAN_RETAIL_DEMO.ANALYTICS.GET_FIVETRAN_CONNECTOR_STATUS(VARCHAR) TO ROLE APP_ROLE;
GRANT USAGE ON FUNCTION FIVETRAN_RETAIL_DEMO.ANALYTICS.GET_FIVETRAN_SYNC_HISTORY(VARCHAR) TO ROLE APP_ROLE;
GRANT USAGE ON FUNCTION FIVETRAN_RETAIL_DEMO.ANALYTICS.TRIGGER_FIVETRAN_SYNC(VARCHAR) TO ROLE APP_ROLE;

-- Managed MCP server (for external MCP clients)
GRANT USAGE ON MCP SERVER FIVETRAN_RETAIL_DEMO.ANALYTICS.RETAIL_MCP_SERVER TO ROLE APP_ROLE;
