-- =====================================================================
-- FreeWheel-style Semantic Model Testing Script
-- =====================================================================
-- Validates verified queries and core KPIs for the synthetic dataset
-- =====================================================================

USE DATABASE FREEWHEEL_DATA_PLATFORM;

-- 1) High-level record counts
SELECT '=== RECORD COUNTS ===' AS section;
SELECT 'Auctions' AS table_name, COUNT(*) AS row_count FROM EXCHANGE_LOGS.AUCTIONS
UNION ALL SELECT 'Bids', COUNT(*) FROM EXCHANGE_LOGS.BIDS
UNION ALL SELECT 'Wins/Impressions', COUNT(*) FROM EXCHANGE_LOGS.WINS_IMPRESSIONS
UNION ALL SELECT 'Losses', COUNT(*) FROM EXCHANGE_LOGS.LOSSES
UNION ALL SELECT 'Conversions', COUNT(*) FROM EXCHANGE_LOGS.CONVERSIONS
UNION ALL SELECT 'Campaigns', COUNT(*) FROM AD_SALES.CAMPAIGNS
UNION ALL SELECT 'Advertisers', COUNT(*) FROM AD_SALES.ADVERTISERS;

-- 2) Campaign performance last 365 days
SELECT '=== CAMPAIGN PERFORMANCE (L365D) ===' AS section;
SELECT i.CAMPAIGN_ID, c.CAMPAIGN_NAME,
       ROUND(SUM(i.CLEARING_PRICE_CPM / 1000), 2) AS spend_usd,
       COUNT(*) AS impressions,
       SUM(CASE WHEN i.WAS_CLICKED THEN 1 ELSE 0 END) AS clicks,
       COUNT(v.CONVERSION_ID) AS conversions,
       ROUND(SUM(CASE WHEN i.WAS_VIEWABLE THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) * 100, 2) AS viewability_pct,
       ROUND(SUM(CASE WHEN i.WAS_CLICKED THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) * 100, 2) AS ctr_pct,
       CASE WHEN COUNT(*) > 0 THEN ROUND((SUM(i.CLEARING_PRICE_CPM / 1000) / COUNT(*)) * 1000, 2) ELSE 0 END AS ecpm,
       CASE WHEN COUNT(v.CONVERSION_ID) > 0 THEN ROUND(SUM(i.CLEARING_PRICE_CPM / 1000) / COUNT(v.CONVERSION_ID), 2) ELSE NULL END AS cpa
FROM EXCHANGE_LOGS.WINS_IMPRESSIONS i
LEFT JOIN EXCHANGE_LOGS.CONVERSIONS v ON v.IMPRESSION_ID = i.IMPRESSION_ID
LEFT JOIN AD_SALES.CAMPAIGNS c ON c.CAMPAIGN_ID = i.CAMPAIGN_ID
WHERE i.IMPRESSION_TIMESTAMP >= DATEADD(day, -365, CURRENT_DATE())
GROUP BY i.CAMPAIGN_ID, c.CAMPAIGN_NAME
ORDER BY spend_usd DESC;

-- 3) Win rate by supply source
SELECT '=== WIN RATE BY SSP ===' AS section;
SELECT a.SSP_ID,
       COUNT(DISTINCT i.IMPRESSION_ID) AS wins,
       COUNT(DISTINCT a.AUCTION_ID) AS auctions,
       ROUND(COUNT(DISTINCT i.IMPRESSION_ID) / NULLIF(COUNT(DISTINCT a.AUCTION_ID), 0) * 100, 2) AS win_rate_pct
FROM EXCHANGE_LOGS.AUCTIONS a
LEFT JOIN EXCHANGE_LOGS.WINS_IMPRESSIONS i ON a.AUCTION_ID = i.AUCTION_ID
GROUP BY a.SSP_ID
ORDER BY win_rate_pct DESC;

-- 4) Pricing pressure by channel
SELECT '=== PRICING PRESSURE BY CHANNEL (LAST QUARTER) ===' AS section;
SELECT a.CHANNEL,
       ROUND(AVG(b.BID_PRICE_CPM), 2) AS avg_bid_cpm,
       ROUND(AVG(a.FLOOR_PRICE_CPM), 2) AS avg_floor_cpm,
       ROUND(AVG(b.BID_PRICE_CPM - a.FLOOR_PRICE_CPM), 2) AS avg_bid_minus_floor
FROM EXCHANGE_LOGS.AUCTIONS a
JOIN EXCHANGE_LOGS.BIDS b ON a.AUCTION_ID = b.AUCTION_ID
WHERE a.AUCTION_TIMESTAMP >= DATEADD(quarter, -1, CURRENT_DATE())
GROUP BY a.CHANNEL
ORDER BY avg_bid_minus_floor DESC;

-- 5) Pacing vs budget (current month)
SELECT '=== PACING VS BUDGET (CURRENT MONTH) ===' AS section;
WITH spend AS (
  SELECT CAMPAIGN_ID, SUM(CLEARING_PRICE_CPM / 1000) AS spend_usd
  FROM EXCHANGE_LOGS.WINS_IMPRESSIONS
  WHERE DATE_TRUNC('month', IMPRESSION_TIMESTAMP) = DATE_TRUNC('month', CURRENT_DATE())
  GROUP BY CAMPAIGN_ID
)
SELECT c.CAMPAIGN_ID, c.CAMPAIGN_NAME, c.TOTAL_BUDGET_USD,
       COALESCE(s.spend_usd, 0) AS month_spend_usd,
       ROUND(COALESCE(s.spend_usd, 0) / NULLIF(c.TOTAL_BUDGET_USD, 0) * 100, 2) AS pct_of_budget
FROM AD_SALES.CAMPAIGNS c
LEFT JOIN spend s ON s.CAMPAIGN_ID = c.CAMPAIGN_ID
WHERE DATE_TRUNC('month', CURRENT_DATE()) BETWEEN DATE_TRUNC('month', c.START_DATE) AND DATE_TRUNC('month', c.END_DATE)
ORDER BY pct_of_budget DESC;

-- 6) Data quality checks
SELECT '=== DATA QUALITY: REFERENTIAL INTEGRITY ===' AS section;
-- Auctions to Bids
SELECT 'Bids → Auctions' AS relationship,
       COUNT(DISTINCT b.AUCTION_ID) AS child_keys,
       COUNT(DISTINCT a.AUCTION_ID) AS parent_keys,
       COUNT(DISTINCT b.AUCTION_ID) - COUNT(DISTINCT CASE WHEN a.AUCTION_ID IS NOT NULL THEN b.AUCTION_ID END) AS orphaned
FROM EXCHANGE_LOGS.BIDS b
LEFT JOIN EXCHANGE_LOGS.AUCTIONS a ON a.AUCTION_ID = b.AUCTION_ID
UNION ALL
-- Wins to Bids
SELECT 'Wins → Bids',
       COUNT(DISTINCT w.BID_ID),
       COUNT(DISTINCT b.BID_ID),
       COUNT(DISTINCT w.BID_ID) - COUNT(DISTINCT CASE WHEN b.BID_ID IS NOT NULL THEN w.BID_ID END)
FROM EXCHANGE_LOGS.WINS_IMPRESSIONS w
LEFT JOIN EXCHANGE_LOGS.BIDS b ON b.BID_ID = w.BID_ID
UNION ALL
-- Conversions to Wins
SELECT 'Conversions → Wins',
       COUNT(DISTINCT v.IMPRESSION_ID),
       COUNT(DISTINCT w.IMPRESSION_ID),
       COUNT(DISTINCT v.IMPRESSION_ID) - COUNT(DISTINCT CASE WHEN w.IMPRESSION_ID IS NOT NULL THEN v.IMPRESSION_ID END)
FROM EXCHANGE_LOGS.CONVERSIONS v
LEFT JOIN EXCHANGE_LOGS.WINS_IMPRESSIONS w ON w.IMPRESSION_ID = v.IMPRESSION_ID;

-- 7) Final summary
SELECT '===================================================' AS divider;
SELECT 'FREEWHEEL ADTECH' AS title;
SELECT 'SEMANTIC MODEL TESTING COMPLETED' AS status;
SELECT '===================================================' AS divider;


