-- ============================================================
-- Cortex AI Cost Dashboard - Snowsight SQL Queries  v2.1
-- ============================================================
-- HOW TO USE:
-- 1. Go to Snowsight > Dashboards > + Dashboard
-- 2. Add a "New Tile from Worksheet" for each query below
-- 3. Set the chart type as noted in each section
-- 4. Add date range filter widget: :date_start and :date_end
-- 5. Update the fully-qualified view name below to match your
--    database and schema (default: CORTEX_AI_USAGE.CORTEX_COST)
--
-- SERVICE_TYPES in v2.1:
--   CORTEX AISQL, CORTEX ANALYST, CORTEX AGENT, CORTEX SEARCH,
--   FINE TUNING, DOCUMENT AI, CORTEX REST API, CORTEX CODE CLI,
--   PROVISIONED THROUGHPUT
-- ============================================================

-- TILE 1: KPI Summary (use as Scorecard tiles - one per metric)
-- Chart type: Scorecard
SELECT
    ROUND(SUM(COALESCE(COMPONENT_CREDITS, 0)), 2) AS TOTAL_CREDITS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end;

-- Scorecard: Unique Users
SELECT
    COUNT(DISTINCT END_USER_NAME) AS UNIQUE_USERS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end;

-- Scorecard: Total Records
SELECT
    COUNT(*) AS TOTAL_RECORDS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end;

-- Scorecard: Service Types
SELECT
    COUNT(DISTINCT SERVICE_TYPE) AS SERVICE_TYPES
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end;

-- Scorecard: Total Tokens
SELECT
    SUM(COALESCE(TOTAL_TOKENS, 0)) AS TOTAL_TOKENS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end;


-- TILE 2: Credits Over Time (Monthly)
-- Chart type: Bar chart, X=PERIOD, Y=CREDITS. Add line for CUMULATIVE_CREDITS.
SELECT
    DATE_TRUNC('MONTH', START_TIME) AS PERIOD,
    ROUND(SUM(COALESCE(COMPONENT_CREDITS, 0)), 2) AS CREDITS,
    ROUND(SUM(SUM(COALESCE(COMPONENT_CREDITS, 0))) OVER (ORDER BY DATE_TRUNC('MONTH', START_TIME)), 2) AS CUMULATIVE_CREDITS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end
GROUP BY DATE_TRUNC('MONTH', START_TIME)
ORDER BY 1;


-- TILE 3: Credits by Service Type
-- Chart type: Bar chart (horizontal), X=CREDITS, Y=SERVICE_TYPE
SELECT
    SERVICE_TYPE,
    ROUND(SUM(COALESCE(COMPONENT_CREDITS, 0)), 2) AS CREDITS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end
GROUP BY 1
ORDER BY 2 DESC;


-- TILE 4: Credits by Cost Component
-- Chart type: Bar chart (horizontal), X=CREDITS, Y=COST_COMPONENT
SELECT
    COST_COMPONENT,
    ROUND(SUM(COALESCE(COMPONENT_CREDITS, 0)), 2) AS CREDITS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end
GROUP BY 1
ORDER BY 2 DESC;


-- TILE 5: Top 10 Users by Credits
-- Chart type: Bar chart (horizontal), X=CREDITS, Y=END_USER_NAME
SELECT
    END_USER_NAME,
    ROUND(SUM(COALESCE(COMPONENT_CREDITS, 0)), 2) AS CREDITS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end
  AND END_USER_NAME IS NOT NULL AND END_USER_NAME != ''
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;


-- TILE 6: Cortex Agent Usage
-- Chart type: Bar chart (horizontal), X=CREDITS, Y=AGENT_NAME
SELECT
    CASE
        WHEN COMPONENT_OBJECT_NAME IS NOT NULL AND COMPONENT_OBJECT_NAME != ''
        THEN COMPONENT_OBJECT_NAME
        ELSE 'Unnamed Agent'
    END AS AGENT_NAME,
    ROUND(SUM(COALESCE(COMPONENT_CREDITS, 0)), 2) AS CREDITS,
    COUNT(*) AS REQUESTS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end
  AND SERVICE_TYPE = 'CORTEX AGENT'
GROUP BY 1
ORDER BY 2 DESC;


-- TILE 7: Top 10 Objects by Credits
-- Chart type: Bar chart (horizontal), X=CREDITS, Y=OBJECT_DISPLAY
SELECT
    SERVICE_TYPE || ' | ' || COALESCE(COMPONENT_OBJECT_NAME, '') AS OBJECT_DISPLAY,
    ROUND(SUM(COALESCE(COMPONENT_CREDITS, 0)), 2) AS CREDITS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;


-- TILE 8: Daily Trend by Service Type (stacked)
-- Chart type: Stacked bar, X=DAY, Y=CREDITS, Color=SERVICE_TYPE
SELECT
    DATE_TRUNC('DAY', START_TIME)::DATE AS DAY,
    SERVICE_TYPE,
    ROUND(SUM(COALESCE(COMPONENT_CREDITS, 0)), 2) AS CREDITS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end
GROUP BY 1, 2
ORDER BY 1, 2;


-- TILE 9: Tokens by Service Type
-- Chart type: Bar chart (horizontal), X=TOTAL_TOKENS, Y=SERVICE_TYPE
SELECT
    SERVICE_TYPE,
    SUM(COALESCE(INPUT_TOKENS, 0)) AS INPUT_TOKENS,
    SUM(COALESCE(OUTPUT_TOKENS, 0)) AS OUTPUT_TOKENS,
    SUM(COALESCE(TOTAL_TOKENS, 0)) AS TOTAL_TOKENS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end
  AND TOTAL_TOKENS > 0
GROUP BY 1
ORDER BY 4 DESC;


-- TILE 10: Detailed Usage Table
-- Chart type: Table
SELECT
    START_TIME,
    END_USER_NAME,
    SERVICE_TYPE,
    COST_COMPONENT,
    COMPONENT_DESCRIPTION,
    COMPONENT_OBJECT_NAME,
    ROUND(COALESCE(COMPONENT_CREDITS, 0), 4) AS CREDITS,
    COALESCE(INPUT_TOKENS, 0) AS INPUT_TOKENS,
    COALESCE(OUTPUT_TOKENS, 0) AS OUTPUT_TOKENS,
    COALESCE(TOTAL_TOKENS, 0) AS TOTAL_TOKENS
FROM CORTEX_AI_USAGE.CORTEX_COST.CORTEX_AI_SUMMARY_COST_VIEW
WHERE START_TIME >= :date_start AND START_TIME <= :date_end
ORDER BY START_TIME DESC
LIMIT 500;
