-- Comcast Revenue Semantic Model - Comprehensive Data Setup
-- This script creates the Comcast Revenue database, schema, tables, synthetic data, views, and validation queries

-- 1) Database and schema
CREATE DATABASE IF NOT EXISTS COMCAST_REVENUE;
USE DATABASE COMCAST_REVENUE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
USE SCHEMA ANALYTICS;

-- 2) Table definitions
CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    PRODUCT_CATEGORY VARCHAR(50),
    BASE_PRICE DECIMAL(10,2),
    SERVICE_TYPE VARCHAR(30)
);

CREATE OR REPLACE TABLE PROMOTION_TYPES (
    PROMO_CODE VARCHAR(30) PRIMARY KEY,
    PROMO_NAME VARCHAR(100),
    DISCOUNT_TYPE VARCHAR(20), -- PERCENTAGE, FIXED_AMOUNT, FREE_MONTHS
    DISCOUNT_VALUE DECIMAL(10,2),
    DURATION_MONTHS INTEGER,
    APPLICABLE_PRODUCTS VARCHAR(500)
);

CREATE OR REPLACE TABLE SERVICE_AREAS (
    AREA_ID VARCHAR(20) PRIMARY KEY,
    CITY VARCHAR(100),
    STATE VARCHAR(10),
    REGION VARCHAR(30),
    LAT NUMBER(10,6),
    LON NUMBER(10,6)
);

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(15) PRIMARY KEY,
    SERVICE_CITY VARCHAR(100),
    SERVICE_STATE VARCHAR(10),
    SERVICE_REGION VARCHAR(30),
    CUSTOMER_LAT NUMBER(10,6),
    CUSTOMER_LON NUMBER(10,6)
);

CREATE OR REPLACE TABLE ORDER_SYSTEM_DATA (
    ORDER_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(15),
    ORDER_DATE DATE,
    PRODUCT_ID VARCHAR(20),
    PROMO_CODE VARCHAR(30),
    BASE_AMOUNT DECIMAL(10,2),
    DISCOUNT_AMOUNT DECIMAL(10,2),
    FINAL_AMOUNT DECIMAL(10,2),
    ORDER_STATUS VARCHAR(20),
    LINE_NUMBER VARCHAR(20),
    ACCOUNT_ID VARCHAR(25),
    PROMO_START_CYCLE INTEGER,
    PROMO_DURATION_MONTHS INTEGER,
    FIRST_BILL_FLAG BOOLEAN
);

CREATE OR REPLACE TABLE BILLING_SYSTEM_DATA (
    BILLING_ID VARCHAR(25) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(15),
    BILLING_DATE DATE,
    PRODUCT_ID VARCHAR(20),
    PROMO_CODE VARCHAR(30),
    BASE_AMOUNT DECIMAL(10,2),
    DISCOUNT_AMOUNT DECIMAL(10,2),
    FINAL_AMOUNT DECIMAL(10,2),
    BILLING_CYCLE VARCHAR(10),
    BILLING_CYCLE_NUMBER INTEGER,
    LINE_NUMBER VARCHAR(20),
    ACCOUNT_ID VARCHAR(25),
    PROMO_APPLIED_CYCLE INTEGER,
    PROMO_DURATION_MONTHS INTEGER
);

-- 3) Synthetic data generation with realistic business values
-- Products
INSERT INTO PRODUCTS VALUES
('XFIN-INT-1G', 'Xfinity Internet Gigabit', 'Internet', 89.99, 'Residential'),
('XFIN-INT-600', 'Xfinity Internet Superfast', 'Internet', 69.99, 'Residential'),
('XFIN-INT-200', 'Xfinity Internet Fast', 'Internet', 49.99, 'Residential'),
('XFIN-INT-100', 'Xfinity Internet Performance', 'Internet', 39.99, 'Residential'),
('XFIN-TV-X1', 'Xfinity X1 TV Premier', 'TV', 139.99, 'Residential'),
('XFIN-TV-ULT', 'Xfinity TV Ultimate', 'TV', 119.99, 'Residential'),
('XFIN-TV-CHOICE', 'Xfinity TV Choice', 'TV', 79.99, 'Residential'),
('XFIN-TV-STARTER', 'Xfinity TV Starter', 'TV', 59.99, 'Residential'),
('XFIN-MOB-UNL-PLUS', 'Xfinity Mobile Unlimited Plus', 'Mobile', 85.00, 'Mobile'),
('XFIN-MOB-UNL', 'Xfinity Mobile Unlimited', 'Mobile', 65.00, 'Mobile'),
('XFIN-MOB-BYG', 'Xfinity Mobile By the Gig', 'Mobile', 20.00, 'Mobile'),
('XFIN-MOB-SHARED', 'Xfinity Mobile Shared Data', 'Mobile', 45.00, 'Mobile'),
('XFIN-HOME-SEC-PLUS', 'Xfinity Home Security Plus', 'Security', 59.99, 'Residential'),
('XFIN-HOME-SEC', 'Xfinity Home Security Basic', 'Security', 39.99, 'Residential'),
('XFIN-BUS-INT-1G', 'Business Internet Gigabit Pro', 'Internet', 299.95, 'Business'),
('XFIN-BUS-INT-500', 'Business Internet 500', 'Internet', 199.95, 'Business'),
('XFIN-BUS-VOICE', 'Business VoiceEdge Select', 'Voice', 39.99, 'Business'),
('XFIN-STREAM', 'Peacock Premium Plus', 'Streaming', 11.99, 'Residential'),
('XFIN-TRIPLE-PLAY', 'Xfinity Triple Play Bundle', 'Bundle', 199.99, 'Residential'),
('XFIN-DOUBLE-PLAY', 'Xfinity Double Play Bundle', 'Bundle', 139.99, 'Residential');

-- Promotion types with realistic Comcast offers
INSERT INTO PROMOTION_TYPES VALUES
('NEW-CUST-INT-PROMO', 'New Customer Internet Promo', 'FIXED_AMOUNT', 20.00, 12, 'XFIN-INT-1G,XFIN-INT-600,XFIN-INT-200'),
('TRIPLE-PLAY-BUNDLE', 'Triple Play Bundle Savings', 'FIXED_AMOUNT', 50.00, 24, 'XFIN-TRIPLE-PLAY'),
('DOUBLE-PLAY-PROMO', 'Double Play Special Offer', 'FIXED_AMOUNT', 30.00, 18, 'XFIN-DOUBLE-PLAY'),
('LOYAL-CUSTOMER-DISC', 'Loyalty Rewards Discount', 'PERCENTAGE', 15.00, 12, 'ALL'),
('FIRST-RESPONDER', 'First Responder Appreciation', 'PERCENTAGE', 25.00, 999, 'ALL'),
('STUDENT-INTERNET', 'Student Internet Special', 'PERCENTAGE', 30.00, 9, 'XFIN-INT-200,XFIN-INT-100'),
('MOBILE-LINE-FREE', 'One Line Free Xfinity Mobile', 'FREE_MONTHS', 3.00, 12, 'XFIN-MOB-UNL,XFIN-MOB-BYG'),
('MOBILE-BYOD-CREDIT', 'Bring Your Own Device Credit', 'FIXED_AMOUNT', 50.00, 1, 'XFIN-MOB-UNL,XFIN-MOB-BYG'),
('BUS-STARTER-PACK', 'Business Starter Package', 'FIXED_AMOUNT', 100.00, 12, 'XFIN-BUS-INT-500,XFIN-BUS-VOICE'),
('SECURITY-INSTALL-FREE', 'Free Security Installation', 'FIXED_AMOUNT', 99.00, 1, 'XFIN-HOME-SEC,XFIN-HOME-SEC-PLUS'),
('PEACOCK-FREE-TRIAL', 'Free Peacock Premium Trial', 'FREE_MONTHS', 6.00, 6, 'XFIN-STREAM'),
('REFER-FRIEND-CREDIT', 'Refer a Friend Account Credit', 'FIXED_AMOUNT', 100.00, 1, 'ALL'),
('SENIOR-DISCOUNT', 'Senior Citizen Discount', 'PERCENTAGE', 10.00, 999, 'XFIN-INT-100,XFIN-TV-STARTER'),
('AUTOPAY-DISCOUNT', 'AutoPay & Paperless Billing', 'FIXED_AMOUNT', 10.00, 999, 'ALL'),
('MOBILE-FAMILY-PLAN', 'Family Plan 4th Line Free', 'FREE_MONTHS', 12.00, 12, 'XFIN-MOB-UNL');

-- Service areas
INSERT INTO SERVICE_AREAS (AREA_ID, CITY, STATE, REGION, LAT, LON) VALUES
('AREA-PHL', 'Philadelphia', 'PA', 'Northeast', 39.952600, -75.165200),
('AREA-CHI', 'Chicago', 'IL', 'Midwest', 41.878100, -87.629800),
('AREA-DC', 'Washington', 'DC', 'Northeast', 38.907200, -77.036900),
('AREA-SF', 'San Francisco', 'CA', 'West', 37.774900, -122.419400),
('AREA-BOS', 'Boston', 'MA', 'Northeast', 42.360100, -71.058900),
('AREA-DEN', 'Denver', 'CO', 'West', 39.739200, -104.990300),
('AREA-ATL', 'Atlanta', 'GA', 'Southeast', 33.749000, -84.388000),
('AREA-MIA', 'Miami', 'FL', 'Southeast', 25.761700, -80.191800),
('AREA-SEA', 'Seattle', 'WA', 'West', 47.606200, -122.332100),
('AREA-DET', 'Detroit', 'MI', 'Midwest', 42.331400, -83.045800),
('AREA-HOU', 'Houston', 'TX', 'South', 29.760400, -95.369800),
('AREA-NYC', 'New York', 'NY', 'Northeast', 40.712800, -74.006000);

-- Customers synthesized around service area centers for realism
INSERT INTO CUSTOMERS
SELECT 
  'CUST-' || LPAD(100000 + SEQ4(), 6, '0') AS CUSTOMER_ID,
  sa.CITY AS SERVICE_CITY,
  sa.STATE AS SERVICE_STATE,
  sa.REGION AS SERVICE_REGION,
  -- Add small random geo offsets (~11km std dev)
  (sa.LAT + (UNIFORM(-1000,1000,RANDOM())/10000.0))::NUMBER(10,6) AS CUSTOMER_LAT,
  (sa.LON + (UNIFORM(-1000,1000,RANDOM())/10000.0))::NUMBER(10,6) AS CUSTOMER_LON
FROM SERVICE_AREAS sa
CROSS JOIN TABLE(GENERATOR(ROWCOUNT => 100)) g; -- ~1200 customers total

-- Orders (~2000 rows) with Fabio's use case fields
INSERT INTO ORDER_SYSTEM_DATA
SELECT
    'ORD-' || LPAD(SEQ4(), 8, '0') AS ORDER_ID,
    c.CUSTOMER_ID,
    DATEADD(day, -UNIFORM(1, 90, RANDOM()), CURRENT_DATE()) AS ORDER_DATE,
    p.PRODUCT_ID,
    CASE WHEN UNIFORM(1,100,RANDOM()) <= 75 THEN 
        CASE UNIFORM(1,15,RANDOM())
            WHEN 1 THEN 'NEW-CUST-INT-PROMO'
            WHEN 2 THEN 'TRIPLE-PLAY-BUNDLE'
            WHEN 3 THEN 'DOUBLE-PLAY-PROMO'
            WHEN 4 THEN 'LOYAL-CUSTOMER-DISC'
            WHEN 5 THEN 'MOBILE-LINE-FREE'
            WHEN 6 THEN 'STUDENT-INTERNET'
            WHEN 7 THEN 'FIRST-RESPONDER'
            WHEN 8 THEN 'AUTOPAY-DISCOUNT'
            WHEN 9 THEN 'MOBILE-BYOD-CREDIT'
            WHEN 10 THEN 'SECURITY-INSTALL-FREE'
            WHEN 11 THEN 'SENIOR-DISCOUNT'
            WHEN 12 THEN 'MOBILE-FAMILY-PLAN'
            WHEN 13 THEN 'PEACOCK-FREE-TRIAL'
            WHEN 14 THEN 'REFER-FRIEND-CREDIT'
            ELSE 'NEW-CUST-INT-PROMO'
        END
    ELSE NULL END AS PROMO_CODE,
    p.BASE_PRICE AS BASE_AMOUNT,
    CASE WHEN UNIFORM(1,100,RANDOM()) <= 70 THEN ROUND(p.BASE_PRICE * UNIFORM(10,50,RANDOM())/100, 2) ELSE 0 END AS DISCOUNT_AMOUNT,
    0 AS FINAL_AMOUNT,
    'ACTIVE' AS ORDER_STATUS,
    CASE 
        WHEN p.PRODUCT_ID LIKE '%MOB%' AND UNIFORM(1,100,RANDOM()) <= 8 THEN 
            -- 8% chance of duplicate line number - use fixed values to ensure duplicates exist
            CASE UNIFORM(1,5,RANDOM())
                WHEN 1 THEN '2155551234'  -- Philadelphia duplicate
                WHEN 2 THEN '7732569876'  -- New Jersey duplicate  
                WHEN 3 THEN '6104445555'  -- Suburban Philadelphia duplicate
                WHEN 4 THEN '8562223456'  -- South Jersey duplicate
                ELSE '4845556789'         -- Delaware County duplicate
            END
        WHEN p.PRODUCT_ID LIKE '%MOB%' THEN 
            -- Generate unique line numbers for remaining mobile products
            LPAD(UNIFORM(2000000000, 9999999999, RANDOM()), 10, '0')
        ELSE NULL 
    END AS LINE_NUMBER,
    'ACCT-' || c.CUSTOMER_ID AS ACCOUNT_ID,
    1 AS PROMO_START_CYCLE,
    CASE 
        WHEN PROMO_CODE IS NOT NULL THEN 12
        ELSE 12 
    END AS PROMO_DURATION_MONTHS,
    CASE WHEN UNIFORM(1,100,RANDOM()) <= 15 THEN TRUE ELSE FALSE END AS FIRST_BILL_FLAG
FROM TABLE(GENERATOR(ROWCOUNT => 2000)) g
CROSS JOIN LATERAL (
    SELECT PRODUCT_ID, BASE_PRICE FROM PRODUCTS ORDER BY RANDOM() LIMIT 1
) p
CROSS JOIN LATERAL (
    SELECT CUSTOMER_ID FROM CUSTOMERS ORDER BY RANDOM() LIMIT 1
) c;

UPDATE ORDER_SYSTEM_DATA SET FINAL_AMOUNT = BASE_AMOUNT - DISCOUNT_AMOUNT;

-- Billing with intentional discrepancies and 5% missing, plus Fabio's use cases
INSERT INTO BILLING_SYSTEM_DATA
SELECT 
    'BILL-' || ORDER_ID AS BILLING_ID,
    CUSTOMER_ID,
    DATEADD(day, UNIFORM(1, 15, RANDOM()), ORDER_DATE) AS BILLING_DATE,
    PRODUCT_ID,
    PROMO_CODE,
    BASE_AMOUNT,
    CASE 
        -- Create realistic billing discrepancies
        WHEN UNIFORM(1,100,RANDOM()) <= 70 THEN DISCOUNT_AMOUNT  -- 70% exact match
        WHEN UNIFORM(1,100,RANDOM()) <= 80 THEN ROUND(DISCOUNT_AMOUNT * UNIFORM(90,110,RANDOM())/100, 2)  -- Minor calculation differences
        WHEN UNIFORM(1,100,RANDOM()) <= 85 THEN ROUND(DISCOUNT_AMOUNT * UNIFORM(50,150,RANDOM())/100, 2)  -- Significant variances
        WHEN UNIFORM(1,100,RANDOM()) <= 90 THEN 0  -- Promotion not applied in billing
        WHEN UNIFORM(1,100,RANDOM()) <= 95 THEN ROUND(DISCOUNT_AMOUNT * 2, 2)  -- Double billing error
        ELSE ROUND(DISCOUNT_AMOUNT + UNIFORM(10,50,RANDOM()), 2)  -- Additional incorrect charges
    END AS DISCOUNT_AMOUNT,
    0 AS FINAL_AMOUNT,
    'MONTHLY' AS BILLING_CYCLE,
    CASE 
        WHEN UNIFORM(1,100,RANDOM()) <= 95 THEN 1  -- First bill cycle
        WHEN UNIFORM(1,100,RANDOM()) <= 10 THEN 2  -- Promo applied late to second bill  
        ELSE 1
    END AS BILLING_CYCLE_NUMBER,
    CASE 
        WHEN LINE_NUMBER IS NOT NULL AND UNIFORM(1,100,RANDOM()) <= 8 THEN 
            -- 8% chance of duplicate line number issue - realistic scenarios
            CASE UNIFORM(1,5,RANDOM())
                WHEN 1 THEN '2155551234'  -- Common Philadelphia area duplicate
                WHEN 2 THEN '7732569876'  -- New Jersey area duplicate  
                WHEN 3 THEN '6104445555'  -- Suburban Philadelphia duplicate
                WHEN 4 THEN '8562223456'  -- South Jersey duplicate
                ELSE '4845556789'         -- Delaware County duplicate
            END
        WHEN LINE_NUMBER IS NOT NULL AND UNIFORM(1,100,RANDOM()) <= 3 THEN
            -- 3% chance of wrong account assignment (line exists but wrong account)
            LINE_NUMBER  -- Keep same line but will be flagged as duplicate in reconciliation
        ELSE LINE_NUMBER 
    END AS LINE_NUMBER,
    ACCOUNT_ID,
    CASE 
        -- Promo timing issues - sometimes applied to wrong cycle
        WHEN UNIFORM(1,100,RANDOM()) <= 10 THEN 2  -- 10% applied to cycle 2 instead of 1
        ELSE PROMO_START_CYCLE
    END AS PROMO_APPLIED_CYCLE,
    PROMO_DURATION_MONTHS
FROM ORDER_SYSTEM_DATA
WHERE UNIFORM(1,100,RANDOM()) <= 95; -- 5% missing billing

UPDATE BILLING_SYSTEM_DATA SET FINAL_AMOUNT = BASE_AMOUNT - DISCOUNT_AMOUNT;

-- 4) Views and enrichment
-- Promotion reconciliation view with geo columns
CREATE OR REPLACE VIEW PROMOTION_RECONCILIATION AS
SELECT 
    COALESCE(o.ORDER_ID, 'MISSING-' || b.BILLING_ID) AS RECORD_ID,
    COALESCE(o.CUSTOMER_ID, b.CUSTOMER_ID) AS CUSTOMER_ID,
    COALESCE(o.ORDER_DATE, b.BILLING_DATE) AS TRANSACTION_DATE,
    COALESCE(o.PRODUCT_ID, b.PRODUCT_ID) AS PRODUCT_ID,
    p.PRODUCT_NAME,
    p.PRODUCT_CATEGORY,
    COALESCE(o.PROMO_CODE, b.PROMO_CODE) AS PROMO_CODE,
    pt.PROMO_NAME,
    -- Order amounts
    o.BASE_AMOUNT AS ORDER_BASE_AMOUNT,
    o.DISCOUNT_AMOUNT AS ORDER_DISCOUNT_AMOUNT,
    o.FINAL_AMOUNT AS ORDER_FINAL_AMOUNT,
    -- Billing amounts
    b.BASE_AMOUNT AS BILLING_BASE_AMOUNT,
    b.DISCOUNT_AMOUNT AS BILLING_DISCOUNT_AMOUNT,
    b.FINAL_AMOUNT AS BILLING_FINAL_AMOUNT,
    -- Variances
    COALESCE(o.DISCOUNT_AMOUNT,0) - COALESCE(b.DISCOUNT_AMOUNT,0) AS DISCOUNT_VARIANCE,
    COALESCE(o.FINAL_AMOUNT,0) - COALESCE(b.FINAL_AMOUNT,0) AS FINAL_AMOUNT_VARIANCE,
    ABS(COALESCE(o.DISCOUNT_AMOUNT,0) - COALESCE(b.DISCOUNT_AMOUNT,0)) AS ABS_VARIANCE,
    -- Status (enhanced for Fabio's use cases)
    CASE 
      WHEN o.ORDER_ID IS NULL THEN 'BILLING_ONLY'
      WHEN b.BILLING_ID IS NULL THEN 'ORDER_ONLY'
      WHEN b.PROMO_APPLIED_CYCLE != o.PROMO_START_CYCLE THEN 'PROMO_TIMING_MISMATCH'
      WHEN o.LINE_NUMBER IS NOT NULL AND EXISTS (
          SELECT 1 FROM ORDER_SYSTEM_DATA o2 
          WHERE o2.LINE_NUMBER = o.LINE_NUMBER AND o2.ORDER_ID != o.ORDER_ID
      ) THEN 'DUPLICATE_LINE_NUMBER'
      WHEN ABS(COALESCE(o.DISCOUNT_AMOUNT,0) - COALESCE(b.DISCOUNT_AMOUNT,0)) > 0.01 THEN 'DISCOUNT_MISMATCH'
      WHEN ABS(COALESCE(o.FINAL_AMOUNT,0) - COALESCE(b.FINAL_AMOUNT,0)) > 0.01 THEN 'AMOUNT_MISMATCH'
      ELSE 'MATCHED'
    END AS RECONCILIATION_STATUS,
    -- Risk (enhanced for Fabio's priority cases)
    CASE 
      WHEN o.ORDER_ID IS NULL OR b.BILLING_ID IS NULL THEN 'HIGH'
      WHEN o.FIRST_BILL_FLAG = TRUE AND b.BILLING_CYCLE_NUMBER != 1 THEN 'HIGH'  -- First bill issues are critical
      WHEN b.PROMO_APPLIED_CYCLE != o.PROMO_START_CYCLE THEN 'HIGH'  -- Timing issues
      WHEN o.LINE_NUMBER IS NOT NULL AND EXISTS (
          SELECT 1 FROM ORDER_SYSTEM_DATA o2 
          WHERE o2.LINE_NUMBER = o.LINE_NUMBER AND o2.ORDER_ID != o.ORDER_ID
      ) THEN 'HIGH'  -- Duplicate line numbers
      WHEN ABS(COALESCE(o.DISCOUNT_AMOUNT,0) - COALESCE(b.DISCOUNT_AMOUNT,0)) > 20 THEN 'HIGH'
      WHEN ABS(COALESCE(o.DISCOUNT_AMOUNT,0) - COALESCE(b.DISCOUNT_AMOUNT,0)) > 5 THEN 'MEDIUM'
      ELSE 'LOW'
    END AS RISK_LEVEL,
    -- Geo enrichment from customers
    c.SERVICE_CITY,
    c.SERVICE_STATE,
    c.SERVICE_REGION,
    c.CUSTOMER_LAT,
    c.CUSTOMER_LON
FROM ORDER_SYSTEM_DATA o
FULL OUTER JOIN BILLING_SYSTEM_DATA b ON o.ORDER_ID = REPLACE(b.BILLING_ID, 'BILL-', '')
LEFT JOIN PRODUCTS p ON COALESCE(o.PRODUCT_ID, b.PRODUCT_ID) = p.PRODUCT_ID
LEFT JOIN PROMOTION_TYPES pt ON COALESCE(o.PROMO_CODE, b.PROMO_CODE) = pt.PROMO_CODE
LEFT JOIN CUSTOMERS c ON COALESCE(o.CUSTOMER_ID, b.CUSTOMER_ID) = c.CUSTOMER_ID;

-- Summary view
CREATE OR REPLACE VIEW RECONCILIATION_SUMMARY AS
SELECT 
    'SUMMARY' AS DUMMY_KEY,
    COUNT(*) AS TOTAL_RECORDS,
    SUM(CASE WHEN RECONCILIATION_STATUS = 'MATCHED' THEN 1 ELSE 0 END) AS MATCHED_RECORDS,
    SUM(CASE WHEN RECONCILIATION_STATUS <> 'MATCHED' THEN 1 ELSE 0 END) AS EXCEPTION_RECORDS,
    ROUND(SUM(CASE WHEN RECONCILIATION_STATUS = 'MATCHED' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*),0), 2) AS MATCH_RATE_PCT,
    SUM(ABS(DISCOUNT_VARIANCE)) AS TOTAL_DISCOUNT_VARIANCE,
    SUM(ABS(FINAL_AMOUNT_VARIANCE)) AS TOTAL_AMOUNT_VARIANCE,
    SUM(CASE WHEN RISK_LEVEL = 'HIGH' THEN 1 ELSE 0 END) AS HIGH_RISK_COUNT,
    SUM(CASE WHEN RISK_LEVEL = 'MEDIUM' THEN 1 ELSE 0 END) AS MEDIUM_RISK_COUNT,
    SUM(CASE WHEN RISK_LEVEL = 'LOW' THEN 1 ELSE 0 END) AS LOW_RISK_COUNT
FROM PROMOTION_RECONCILIATION;

-- 5) Data validation queries (reference examples)
-- Count checks
SELECT 'ROW_COUNTS' AS CHECK_TYPE,
       (SELECT COUNT(*) FROM PRODUCTS) AS PRODUCTS,
       (SELECT COUNT(*) FROM PROMOTION_TYPES) AS PROMOTION_TYPES,
       (SELECT COUNT(*) FROM CUSTOMERS) AS CUSTOMERS,
       (SELECT COUNT(*) FROM ORDER_SYSTEM_DATA) AS ORDERS,
       (SELECT COUNT(*) FROM BILLING_SYSTEM_DATA) AS BILLING,
       (SELECT COUNT(*) FROM PROMOTION_RECONCILIATION) AS RECONCILIATION;

-- Referential integrity (orders -> products)
SELECT 'ORDERS_MISSING_PRODUCTS' AS CHECK_TYPE, COUNT(*) AS MISSING
FROM ORDER_SYSTEM_DATA o
LEFT JOIN PRODUCTS p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL;

-- Billing missing orders (intended ~5%)
SELECT 'BILLING_ONLY_RATE' AS CHECK_TYPE,
       SUM(CASE WHEN o.ORDER_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*),0) AS PCT_BILLING_ONLY
FROM BILLING_SYSTEM_DATA b
LEFT JOIN ORDER_SYSTEM_DATA o ON o.ORDER_ID = REPLACE(b.BILLING_ID, 'BILL-', '');

-- Risk distribution sanity
SELECT 'RISK_DISTRIBUTION' AS CHECK_TYPE, RISK_LEVEL, COUNT(*) AS CNT, AVG(ABS(DISCOUNT_VARIANCE)) AS AVG_ABS_VAR
FROM PROMOTION_RECONCILIATION
GROUP BY RISK_LEVEL
ORDER BY CNT DESC;

-- Grants for app usage
GRANT USAGE ON DATABASE COMCAST_REVENUE TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA COMCAST_REVENUE.ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA COMCAST_REVENUE.ANALYTICS TO ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA COMCAST_REVENUE.ANALYTICS TO ROLE ACCOUNTADMIN;
