-- Seed live sample data for Comcast demo to mirror the Streamlit enhanced sample
-- Safe to run multiple times; uses idempotent inserts where practical

-- =============================
-- SECTION 1: COMCAST_REVENUE
-- =============================
USE DATABASE COMCAST_REVENUE;
USE SCHEMA ANALYTICS;

-- 1.1 Ensure reference data exists (minimal set)
-- PRODUCTS
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, BASE_PRICE, SERVICE_TYPE)
SELECT * FROM (
    SELECT 'P-INT-GIG' AS PRODUCT_ID, 'Xfinity Internet Gigabit' AS PRODUCT_NAME, 'Internet' AS PRODUCT_CATEGORY, 120::NUMBER(10,2) AS BASE_PRICE, 'Fixed' AS SERVICE_TYPE UNION ALL
    SELECT 'P-INT-SFAST', 'Xfinity Internet Superfast', 'Internet', 90, 'Fixed' UNION ALL
    SELECT 'P-INT-PERF', 'Xfinity Internet Performance', 'Internet', 70, 'Fixed' UNION ALL
    SELECT 'P-TV-PREM', 'Xfinity X1 TV Premier', 'TV', 110, 'Fixed' UNION ALL
    SELECT 'P-TV-FLEX', 'Xfinity Flex 4K', 'TV', 50, 'Fixed' UNION ALL
    SELECT 'P-TV-START', 'Xfinity X1 Starter', 'TV', 60, 'Fixed' UNION ALL
    SELECT 'P-MOB-UNL', 'Xfinity Mobile Unlimited', 'Mobile', 45, 'Mobile' UNION ALL
    SELECT 'P-MOB-SHARE', 'Xfinity Mobile Shared Data', 'Mobile', 35, 'Mobile' UNION ALL
    SELECT 'P-MOB-BTG', 'Xfinity Mobile By The Gig', 'Mobile', 25, 'Mobile' UNION ALL
    SELECT 'P-BUN-TRI', 'Triple Play Ultimate', 'Bundle', 199, 'Bundle' UNION ALL
    SELECT 'P-BUN-DBL', 'Double Play Internet+TV', 'Bundle', 149, 'Bundle' UNION ALL
    SELECT 'P-BUN-QUAD', 'Quad Play Complete', 'Bundle', 249, 'Bundle'
) s
WHERE NOT EXISTS (
  SELECT 1 FROM PRODUCTS p WHERE p.PRODUCT_ID = s.PRODUCT_ID
);

-- PROMOTION_TYPES (length 30 on PROMO_CODE per schema)
INSERT INTO PROMOTION_TYPES (PROMO_CODE, PROMO_NAME, DISCOUNT_TYPE, DISCOUNT_VALUE, DURATION_MONTHS, APPLICABLE_PRODUCTS)
SELECT * FROM (
    SELECT 'NEW-INTERNET' AS PROMO_CODE, 'New Customer Internet Promo' AS PROMO_NAME, 'PERCENT' AS DISCOUNT_TYPE, 20 AS DISCOUNT_VALUE, 12 AS DURATION_MONTHS, 'Internet' AS APPLICABLE_PRODUCTS UNION ALL
    SELECT 'TV-PREMIER-10', 'TV Premier $10 Off', 'AMOUNT', 10, 12, 'TV' UNION ALL
    SELECT 'MOBILE-FREE-LINE', 'One Line Free Xfinity Mobile', 'AMOUNT', 45, 1, 'Mobile' UNION ALL
    SELECT 'TRIPLE-BUNDLE', 'Triple Play Bundle Savings', 'AMOUNT', 30, 12, 'Bundle' UNION ALL
    SELECT 'LOYAL-CREDIT', 'Loyalty Credit', 'AMOUNT', 5, 12, 'All'
) s
WHERE NOT EXISTS (
  SELECT 1 FROM PROMOTION_TYPES t WHERE t.PROMO_CODE = s.PROMO_CODE
);

-- CUSTOMERS (lightweight synthetic set)
CREATE TEMP TABLE IF NOT EXISTS TMP_CUSTOMERS AS
SELECT 
  'CUST-'||TO_VARCHAR(100000 + ROW_NUMBER() OVER (ORDER BY 1)) AS CUSTOMER_ID,
  CITY AS SERVICE_CITY,
  STATE AS SERVICE_STATE,
  REGION AS SERVICE_REGION,
  LAT AS CUSTOMER_LAT,
  LON AS CUSTOMER_LON
FROM (
  SELECT 'Boston' CITY,'MA' STATE,'Northeast' REGION, 42.361145 LAT,-71.057083 LON UNION ALL
  SELECT 'New York','NY','Northeast', 40.7128,-74.0060 UNION ALL
  SELECT 'Philadelphia','PA','Northeast',39.9526,-75.1652 UNION ALL
  SELECT 'Atlanta','GA','Southeast',33.7490,-84.3880 UNION ALL
  SELECT 'Miami','FL','Southeast',25.7617,-80.1918 UNION ALL
  SELECT 'Charlotte','NC','Southeast',35.2271,-80.8431 UNION ALL
  SELECT 'Chicago','IL','Midwest',41.8781,-87.6298 UNION ALL
  SELECT 'Detroit','MI','Midwest',42.3314,-83.0458 UNION ALL
  SELECT 'Milwaukee','WI','Midwest',43.0389,-87.9065 UNION ALL
  SELECT 'Los Angeles','CA','West',34.0522,-118.2437 UNION ALL
  SELECT 'San Francisco','CA','West',37.7749,-122.4194 UNION ALL
  SELECT 'Seattle','WA','West',47.6062,-122.3321 UNION ALL
  SELECT 'Phoenix','AZ','Southwest',33.4484,-112.0740 UNION ALL
  SELECT 'Denver','CO','Southwest',39.7392,-104.9903 UNION ALL
  SELECT 'Las Vegas','NV','Southwest',36.1699,-115.1398
) seed;

-- Upsert a bounded customer set (1,500) if missing
INSERT INTO CUSTOMERS (CUSTOMER_ID, SERVICE_CITY, SERVICE_STATE, SERVICE_REGION, CUSTOMER_LAT, CUSTOMER_LON)
SELECT c.CUSTOMER_ID, c.SERVICE_CITY, c.SERVICE_STATE, c.SERVICE_REGION, c.CUSTOMER_LAT, c.CUSTOMER_LON
FROM (
  SELECT CUSTOMER_ID, SERVICE_CITY, SERVICE_STATE, SERVICE_REGION, CUSTOMER_LAT, CUSTOMER_LON
  FROM TMP_CUSTOMERS
  QUALIFY ROW_NUMBER() OVER (ORDER BY RANDOM()) <= 1500
) c
WHERE NOT EXISTS (
  SELECT 1 FROM CUSTOMERS t WHERE t.CUSTOMER_ID = c.CUSTOMER_ID
);

-- 1.2 Generate live sample orders (mirrors Streamlit enhanced probabilities)
CREATE OR REPLACE TEMP TABLE STG_ORDERS AS
WITH base AS (
  SELECT 
    SEQ4() AS I,
    'ORD-'||TO_VARCHAR(500000 + SEQ4()) AS ORDER_ID_RAW
  FROM TABLE(GENERATOR(ROWCOUNT=>2500))
),
choose AS (
  SELECT 
    I,
    ORDER_ID_RAW AS ORDER_ID,
    'CUST-'||TO_VARCHAR(100000 + I) AS CUSTOMER_ID,
    'ACCT-'||TO_VARCHAR(100000 + I) AS ACCOUNT_ID,
    CASE MOD(I,4)
      WHEN 0 THEN 'Internet'
      WHEN 1 THEN 'TV'
      WHEN 2 THEN 'Mobile'
      ELSE 'Bundle'
    END AS PRODUCT_CATEGORY,
    CASE MOD(I,4)
      WHEN 0 THEN 'P-INT-GIG'
      WHEN 1 THEN 'P-TV-PREM'
      WHEN 2 THEN 'P-MOB-UNL'
      ELSE 'P-BUN-DBL'
    END AS PRODUCT_ID,
    CASE MOD(I,5)
      WHEN 0 THEN 'NEW-INTERNET'
      WHEN 1 THEN 'TV-PREMIER-10'
      WHEN 2 THEN 'MOBILE-FREE-LINE'
      WHEN 3 THEN 'TRIPLE-BUNDLE'
      ELSE 'LOYAL-CREDIT'
    END AS PROMO_CODE,
    DATEADD('day', -UNIFORM(0,30,RANDOM()), CURRENT_DATE()) AS ORDER_DATE,
    ROUND(UNIFORM(50,200,RANDOM())::NUMBER(10,2),2) AS BASE_AMOUNT,
    ROUND((UNIFORM(0,30,RANDOM())/100.0) * UNIFORM(50,200,RANDOM())::NUMBER(10,2),2) AS DISCOUNT_AMOUNT_BASE,
    (UNIFORM(0,100,RANDOM())/100.0) AS RND,
    (UNIFORM(0,100,RANDOM())/100.0) AS RND2,
    (UNIFORM(0,100,RANDOM())/100.0) AS RND3
  FROM base
),
enriched AS (
  SELECT 
    I,
    ORDER_ID,
    CUSTOMER_ID,
    ACCOUNT_ID,
    PRODUCT_CATEGORY,
    PRODUCT_ID,
    PROMO_CODE,
    ORDER_DATE,
    BASE_AMOUNT,
    CASE WHEN BASE_AMOUNT < 0 THEN 0 ELSE ROUND(LEAST(BASE_AMOUNT*0.30, GREATEST(0, DISCOUNT_AMOUNT_BASE)),2) END AS ORDER_DISCOUNT_AMOUNT,
    1 AS PROMO_START_CYCLE,
    CASE WHEN RND < 0.5 THEN 12 ELSE 6 END AS PROMO_DURATION_MONTHS,
    CASE WHEN RND < 0.25 THEN TRUE ELSE FALSE END AS FIRST_BILL_FLAG,
    -- Line number: with duplicates for mobile (15%)
    CASE 
      WHEN PRODUCT_CATEGORY='Mobile' AND RND2 < 0.15 THEN 
        CASE MOD(I,5)
          WHEN 0 THEN '(555) 123-4567'
          WHEN 1 THEN '(555) 234-5678'
          WHEN 2 THEN '(555) 345-6789'
          WHEN 3 THEN '(555) 456-7890'
          ELSE '(555) 567-8901'
        END
      ELSE 
        '('||TO_VARCHAR(UNIFORM(200,999,RANDOM()))||') '||TO_CHAR(UNIFORM(200,999,RANDOM()), '000')||'-'||TO_CHAR(UNIFORM(1000,9999,RANDOM()), '0000')
    END AS LINE_NUMBER,
    RND3 AS RND_VARIANCE_PICK
  FROM choose
)
SELECT 
  ORDER_ID,
  CUSTOMER_ID,
  ORDER_DATE,
  PRODUCT_ID,
  PROMO_CODE,
  BASE_AMOUNT,
  ORDER_DISCOUNT_AMOUNT,
  ROUND(BASE_AMOUNT - ORDER_DISCOUNT_AMOUNT,2) AS ORDER_FINAL_AMOUNT,
  'SUBMITTED' AS ORDER_STATUS,
  LINE_NUMBER,
  ACCOUNT_ID,
  PROMO_START_CYCLE,
  PROMO_DURATION_MONTHS,
  FIRST_BILL_FLAG,
  PRODUCT_CATEGORY,
  RND_VARIANCE_PICK
FROM enriched;

-- 1.3 Generate corresponding billing rows with controlled mismatches
CREATE OR REPLACE TEMP TABLE STG_BILLING AS
WITH src AS (
  SELECT * FROM STG_ORDERS
),
variance AS (
  SELECT 
    src.*,
    -- Weighted variance type: if first bill, higher issue rate; else lower
    CASE 
      WHEN FIRST_BILL_FLAG AND RND_VARIANCE_PICK < 0.45 THEN 'perfect_match'
      WHEN FIRST_BILL_FLAG AND RND_VARIANCE_PICK < 0.60 THEN 'minor_diff'
      WHEN FIRST_BILL_FLAG AND RND_VARIANCE_PICK < 0.75 THEN 'promo_not_applied'
      WHEN FIRST_BILL_FLAG AND RND_VARIANCE_PICK < 0.85 THEN 'incorrect_promo'
      WHEN FIRST_BILL_FLAG AND RND_VARIANCE_PICK < 0.90 THEN 'double_billing'
      WHEN FIRST_BILL_FLAG AND RND_VARIANCE_PICK < 0.95 THEN 'proration'
      WHEN FIRST_BILL_FLAG THEN 'bundle_error'
      -- regular bills
      WHEN RND_VARIANCE_PICK < 0.70 THEN 'perfect_match'
      WHEN RND_VARIANCE_PICK < 0.78 THEN 'minor_diff'
      WHEN RND_VARIANCE_PICK < 0.84 THEN 'promo_not_applied'
      WHEN RND_VARIANCE_PICK < 0.90 THEN 'incorrect_promo'
      WHEN RND_VARIANCE_PICK < 0.94 THEN 'double_billing'
      WHEN RND_VARIANCE_PICK < 0.97 THEN 'proration'
      ELSE 'bundle_error'
    END AS VARIANCE_TYPE,
    CASE WHEN UNIFORM(0,100,RANDOM()) < 12 THEN TRUE ELSE FALSE END AS PROMO_TIMING_MISMATCH
  FROM src
)
SELECT 
  'BILL-'||REPLACE(ORDER_ID,'ORD-','') AS BILLING_ID,
  CUSTOMER_ID,
  ORDER_DATE AS BILLING_DATE,
  PRODUCT_ID,
  PROMO_CODE,
  BASE_AMOUNT AS BASE_AMOUNT,
  -- Billing discount by type
  ROUND(
    CASE VARIANCE_TYPE
      WHEN 'perfect_match' THEN ORDER_DISCOUNT_AMOUNT
      WHEN 'minor_diff' THEN ORDER_DISCOUNT_AMOUNT + (UNIFORM(-5,5,RANDOM()))
      WHEN 'promo_not_applied' THEN 0
      WHEN 'incorrect_promo' THEN ORDER_DISCOUNT_AMOUNT * (UNIFORM(0.2,0.8,RANDOM()))
      WHEN 'double_billing' THEN -ORDER_DISCOUNT_AMOUNT
      WHEN 'proration' THEN ORDER_DISCOUNT_AMOUNT * (UNIFORM(0.3,0.8,RANDOM()))
      WHEN 'bundle_error' THEN ORDER_DISCOUNT_AMOUNT + (UNIFORM(15,45,RANDOM()))
    END, 2
  ) AS DISCOUNT_AMOUNT,
  -- Final amount derived from base - billing discount
  ROUND(BASE_AMOUNT - (
    CASE VARIANCE_TYPE
      WHEN 'perfect_match' THEN ORDER_DISCOUNT_AMOUNT
      WHEN 'minor_diff' THEN ORDER_DISCOUNT_AMOUNT + (UNIFORM(-5,5,RANDOM()))
      WHEN 'promo_not_applied' THEN 0
      WHEN 'incorrect_promo' THEN ORDER_DISCOUNT_AMOUNT * (UNIFORM(0.2,0.8,RANDOM()))
      WHEN 'double_billing' THEN -ORDER_DISCOUNT_AMOUNT
      WHEN 'proration' THEN ORDER_DISCOUNT_AMOUNT * (UNIFORM(0.3,0.8,RANDOM()))
      WHEN 'bundle_error' THEN ORDER_DISCOUNT_AMOUNT + (UNIFORM(15,45,RANDOM()))
    END
  ), 2) AS FINAL_AMOUNT,
  '1' AS BILLING_CYCLE,
  CASE WHEN FIRST_BILL_FLAG AND VARIANCE_TYPE <> 'perfect_match' THEN 2 ELSE 1 END AS BILLING_CYCLE_NUMBER,
  LINE_NUMBER,
  ACCOUNT_ID,
  CASE WHEN PROMO_TIMING_MISMATCH THEN (CASE WHEN UNIFORM(0,100,RANDOM()) < 50 THEN 2 ELSE 3 END) ELSE 1 END AS PROMO_APPLIED_CYCLE,
  PROMO_DURATION_MONTHS
FROM variance;

-- 1.4 Insert rows
-- Optionally clear previous synthetic set (uncomment if desired)
-- DELETE FROM BILLING_SYSTEM_DATA WHERE BILLING_ID LIKE 'BILL-%';
-- DELETE FROM ORDER_SYSTEM_DATA WHERE ORDER_ID LIKE 'ORD-%';

INSERT INTO ORDER_SYSTEM_DATA (
  ORDER_ID, CUSTOMER_ID, ORDER_DATE, PRODUCT_ID, PROMO_CODE,
  BASE_AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, ORDER_STATUS,
  LINE_NUMBER, ACCOUNT_ID, PROMO_START_CYCLE, PROMO_DURATION_MONTHS, FIRST_BILL_FLAG
)
SELECT 
  ORDER_ID, CUSTOMER_ID, ORDER_DATE, PRODUCT_ID, PROMO_CODE,
  BASE_AMOUNT, ORDER_DISCOUNT_AMOUNT, ORDER_FINAL_AMOUNT, ORDER_STATUS,
  LINE_NUMBER, ACCOUNT_ID, PROMO_START_CYCLE, PROMO_DURATION_MONTHS, FIRST_BILL_FLAG
FROM STG_ORDERS;

INSERT INTO BILLING_SYSTEM_DATA (
  BILLING_ID, CUSTOMER_ID, BILLING_DATE, PRODUCT_ID, PROMO_CODE,
  BASE_AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, BILLING_CYCLE,
  BILLING_CYCLE_NUMBER, LINE_NUMBER, ACCOUNT_ID, PROMO_APPLIED_CYCLE, PROMO_DURATION_MONTHS
)
SELECT 
  BILLING_ID, CUSTOMER_ID, BILLING_DATE, PRODUCT_ID, PROMO_CODE,
  BASE_AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, BILLING_CYCLE,
  BILLING_CYCLE_NUMBER, LINE_NUMBER, ACCOUNT_ID, PROMO_APPLIED_CYCLE, PROMO_DURATION_MONTHS
FROM STG_BILLING;

-- 1.5 Ensure CUSTOMERS covers all order customers (assign random geo to missing)
INSERT INTO CUSTOMERS (CUSTOMER_ID, SERVICE_CITY, SERVICE_STATE, SERVICE_REGION, CUSTOMER_LAT, CUSTOMER_LON)
SELECT o.CUSTOMER_ID, t.SERVICE_CITY, t.SERVICE_STATE, t.SERVICE_REGION, t.CUSTOMER_LAT, t.CUSTOMER_LON
FROM (
  SELECT DISTINCT CUSTOMER_ID FROM STG_ORDERS
) o
LEFT JOIN CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
JOIN (
  SELECT SERVICE_CITY, SERVICE_STATE, SERVICE_REGION, CUSTOMER_LAT, CUSTOMER_LON,
         ROW_NUMBER() OVER (ORDER BY RANDOM()) AS rn
  FROM TMP_CUSTOMERS
) t
ON 1=1
QUALIFY c.CUSTOMER_ID IS NULL AND ROW_NUMBER() OVER (PARTITION BY o.CUSTOMER_ID ORDER BY RANDOM()) = 1;

-- =============================
-- SECTION 2: COMCAST_DEMO (simpler schema)
-- =============================
USE DATABASE COMCAST_DEMO;
USE SCHEMA RECONCILIATION;

-- Minimal seed for PRODUCTS and PROMOTION_TYPES
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, BASE_PRICE, SERVICE_TYPE)
SELECT * FROM (
    SELECT 'P-INT-GIG' AS PRODUCT_ID,'Xfinity Internet Gigabit' AS PRODUCT_NAME,'Internet' AS PRODUCT_CATEGORY,120 AS BASE_PRICE,'Fixed' AS SERVICE_TYPE UNION ALL
    SELECT 'P-TV-PREM','Xfinity X1 TV Premier','TV',110,'Fixed' UNION ALL
    SELECT 'P-MOB-UNL','Xfinity Mobile Unlimited','Mobile',45,'Mobile' UNION ALL
    SELECT 'P-BUN-DBL','Double Play Internet+TV','Bundle',149,'Bundle'
) s
WHERE NOT EXISTS (SELECT 1 FROM PRODUCTS p WHERE p.PRODUCT_ID = s.PRODUCT_ID);

INSERT INTO PROMOTION_TYPES (PROMO_CODE, PROMO_NAME, DISCOUNT_TYPE, DISCOUNT_VALUE, DURATION_MONTHS, APPLICABLE_PRODUCTS)
SELECT * FROM (
    SELECT 'NEW-INTERNET' AS PROMO_CODE,'New Customer Internet Promo' AS PROMO_NAME,'PERCENT' AS DISCOUNT_TYPE,20 AS DISCOUNT_VALUE,12 AS DURATION_MONTHS,'Internet' AS APPLICABLE_PRODUCTS UNION ALL
    SELECT 'TV-PREMIER-10','TV Premier $10 Off','AMOUNT',10,12,'TV' UNION ALL
    SELECT 'MOBILE-FREE-LINE','One Line Free Xfinity Mobile','AMOUNT',45,1,'Mobile'
) s
WHERE NOT EXISTS (SELECT 1 FROM PROMOTION_TYPES t WHERE t.PROMO_CODE = s.PROMO_CODE);

-- Generate 1500 orders
CREATE OR REPLACE TEMP TABLE DEMO_ORDERS AS
SELECT 
  'ORD-'||TO_VARCHAR(700000 + SEQ4()) AS ORDER_ID,
  'CUST-'||TO_VARCHAR(200000 + SEQ4()) AS CUSTOMER_ID,
  DATEADD('day', -UNIFORM(0,30,RANDOM()), CURRENT_DATE()) AS ORDER_DATE,
  CASE MOD(SEQ4(),4)
    WHEN 0 THEN 'P-INT-GIG'
    WHEN 1 THEN 'P-TV-PREM'
    WHEN 2 THEN 'P-MOB-UNL'
    ELSE 'P-BUN-DBL'
  END AS PRODUCT_ID,
  CASE MOD(SEQ4(),3)
    WHEN 0 THEN 'NEW-INTERNET'
    WHEN 1 THEN 'TV-PREMIER-10'
    ELSE 'MOBILE-FREE-LINE'
  END AS PROMO_CODE,
  ROUND(UNIFORM(50,200,RANDOM())::NUMBER(10,2),2) AS BASE_AMOUNT,
  ROUND(UNIFORM(0,0.3,RANDOM()) * UNIFORM(50,200,RANDOM())::NUMBER(10,2),2) AS DISCOUNT_AMOUNT,
  'SUBMITTED' AS ORDER_STATUS
FROM TABLE(GENERATOR(ROWCOUNT=>1500));

INSERT INTO ORDER_SYSTEM_DATA (
  ORDER_ID, CUSTOMER_ID, ORDER_DATE, PRODUCT_ID, PROMO_CODE, BASE_AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, ORDER_STATUS
)
SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, PRODUCT_ID, PROMO_CODE, BASE_AMOUNT, DISCOUNT_AMOUNT, ROUND(BASE_AMOUNT - DISCOUNT_AMOUNT,2), ORDER_STATUS
FROM DEMO_ORDERS;

-- Billing rows with mismatches similar to enhanced sample
CREATE OR REPLACE TEMP TABLE DEMO_BILLING AS
SELECT 
  'BILL-'||REPLACE(ORDER_ID,'ORD-','') AS BILLING_ID,
  CUSTOMER_ID,
  ORDER_DATE AS BILLING_DATE,
  PRODUCT_ID,
  PROMO_CODE,
  BASE_AMOUNT,
  ROUND(
    CASE 
      WHEN UNIFORM(0,100,RANDOM()) < 60 THEN DISCOUNT_AMOUNT -- perfect
      WHEN UNIFORM(0,100,RANDOM()) < 70 THEN DISCOUNT_AMOUNT + UNIFORM(-5,5,RANDOM())
      WHEN UNIFORM(0,100,RANDOM()) < 78 THEN 0
      WHEN UNIFORM(0,100,RANDOM()) < 85 THEN DISCOUNT_AMOUNT * UNIFORM(0.2,0.8,RANDOM())
      WHEN UNIFORM(0,100,RANDOM()) < 90 THEN -DISCOUNT_AMOUNT
      WHEN UNIFORM(0,100,RANDOM()) < 95 THEN DISCOUNT_AMOUNT * UNIFORM(0.3,0.8,RANDOM())
      ELSE DISCOUNT_AMOUNT + UNIFORM(15,45,RANDOM())
    END,2
  ) AS DISCOUNT_AMOUNT,
  '1' AS BILLING_CYCLE
FROM DEMO_ORDERS;

INSERT INTO BILLING_SYSTEM_DATA (
  BILLING_ID, CUSTOMER_ID, BILLING_DATE, PRODUCT_ID, PROMO_CODE, BASE_AMOUNT, DISCOUNT_AMOUNT, FINAL_AMOUNT, BILLING_CYCLE
)
SELECT 
  BILLING_ID, CUSTOMER_ID, BILLING_DATE, PRODUCT_ID, PROMO_CODE, BASE_AMOUNT, DISCOUNT_AMOUNT,
  ROUND(BASE_AMOUNT - DISCOUNT_AMOUNT,2) AS FINAL_AMOUNT,
  BILLING_CYCLE
FROM DEMO_BILLING;

-- Done. Validate by querying the views in each database.


